name: solana

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: 
    paths:
      - 'solana/**'

env:
  CARGO_TERM_COLOR: always
  RUSTC_VERSION: 1.75.0

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  make-cargo-test-all:
    name: make cargo-test-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
      - name: make cargo-test-all
        run: make cargo-test-all
        working-directory: ./solana

  make-lint:
    name: make lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: clippy, rustfmt
      - name: make lint
        run: make lint
        working-directory: ./solana

  make-check-idl:
    name: make check-idl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: metadaoproject/setup-anchor@v2
        with:
          node-version: "20.11.0"
          solana-cli-version: "1.18.15"
          anchor-version: "0.30.1"
      - name: Set default Rust toolchain
        run: rustup default stable
        working-directory: ./solana
      - name: make check-idl
        run: make check-idl
        working-directory: ./solana

  make-anchor-test:
    name: make anchor-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - uses: metadaoproject/setup-anchor@v2
        with:
          node-version: "20.11.0"
          solana-cli-version: "1.18.15"
          anchor-version: "0.30.1"
      - name: Set default Rust toolchain
        run: rustup default stable
        working-directory: ./solana
      - name: make anchor-test
        run: make anchor-test
        working-directory: ./solana

  make-anchor-test-upgrade:
    name: make anchor-test-upgrade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - uses: metadaoproject/setup-anchor@v2
        with:
          node-version: "20.11.0"
          solana-cli-version: "1.18.15"
          anchor-version: "0.30.1"
      - name: Set default Rust toolchain
        run: rustup default stable
        working-directory: ./solana
      - name: make anchor-test-upgrade
        run: make anchor-test-upgrade
        working-directory: ./solana
